### ISSUE TITLE
dataviz on pypi

### ISSUE THREAD

**Issue by artur-scholz** [ep12/dataviz#1]
Hi,
sorry but I did not find another way to contact you.
I have a Python project that is also named dataviz (https://gitlab.com/librecube/lib/python-dataviz), and which I would like to put on pypi.
However, the name is already reserved by your project, which however seems to be at a stale state.
Would you mind to remove your project from pypi? Of course only if you don't intend to continue your project.
Regards
Artur
artur.scholz@librecube.org

**Comment by ep12** [comment]
Yeah, I definitely want to get to it at some point, but then I can choose another name. I'll remove my package from pypi.

**Comment by ep12** [comment]
Done. Upload yours before anybody else takes the name. I think there already was a `dataviz` package before I reserved the name, so the name is good and easy to come up with.

**Comment by artur-scholz** [comment]
Thanks very much!
